In [1]:
import pandas as pd
import bqplot as bq
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import ipywidgets

Load the 2017 cps file

In [2]:
cps = pd.read_csv('atuscps_2017.csv')

In [3]:
cps.head()

,TUCASEID,TULINENO,GEREG,GEDIV,GESTFIPS,GTMETSTA,GTCBSA,GTCO,HEFAMINC,HEHOUSUT,...,PXPDEMP1,PXNMEMP1,PXPDEMP2,PXNMEMP2,PECERT1,PECERT2,PECERT3,PXCERT1,PXCERT2,PXCERT3
0,20170101170002,1,2,3,26,1,19820,163,8,1,...,1,1,-1,-1,-1,-1,-1,-1,-1,-1
1,20170101170002,2,2,3,26,1,19820,163,8,1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,20170101170012,1,3,5,12,1,45300,57,13,1,...,0,0,0,0,-1,-1,-1,-1,-1,-1
3,20170101170012,2,3,5,12,1,45300,57,13,1,...,1,1,-1,-1,-1,-1,-1,-1,-1,-1
4,20170101170012,3,3,5,12,1,45300,57,13,1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [4]:
summary = pd.read_csv('atussum_2017.csv') #Summary file of 2017

In [5]:
summary.head()

,TUCASEID,TUFINLWGT,TRYHHCHILD,TEAGE,TESEX,PEEDUCA,PTDTRACE,PEHSPNON,GTMETSTA,TELFS,...,t181601,t181699,t181801,t181899,t189999,t500101,t500103,t500105,t500106,t500107
0,20170101170002,5.217551e+06,15,34,2,39,2,2,1,1,...,0,0,0,0,0,0,0,0,0,0
1,20170101170012,3.106847e+06,7,28,2,40,1,2,1,5,...,0,0,0,0,0,0,0,0,0,0
2,20170101170027,1.653409e+07,15,15,1,35,3,2,1,5,...,0,0,0,0,0,0,0,0,0,0
3,20170101170030,1.757071e+07,-1,46,1,39,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
4,20170101170033,1.022275e+06,-1,85,1,44,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [6]:
cps_ = cps.groupby('TUCASEID').GESTFIPS.first().to_frame()

GESTFIPS is the state id which is the fips mapping for the state. bqplot uses fipsmap to identify the states

In [7]:
cps_

                GESTFIPS
TUCASEID
20170101170002        26
20170101170012        12
20170101170027        35
20170101170030        42
20170101170033        53
20170101170074        35
20170101170079        12
20170101170081        31
20170101170090        51
20170101170149        26
20170101170520        25
20170101170521        23
20170101170522        25
20170101170539        13
20170101170551        51
20170101170552        27
20170101170572        18
20170101170574        24
20170101170578         6
20170101170595         4
20170101170596         6
20170101170598        12
20170101170612        39
20170101170615        24
20170101170639        36
20170101170644        22
20170101170651        22
20170101170668        13
20170101170687        12
20170101170688        49
...                  ...
20171212171881        49
20171212171891         6
20171212171894        51
20171212171895        17
20171212171937         6
20171212171938        39
20171212171961        18
20171212171999        45
20171212172005        51
20171212172017        17
20171212172026        46
20171212172030        39
20171212172057         1
20171212172062        53
20171212172072        51
20171212172083        56
20171212172143         8
20171212172206        22
20171212172208        36
20171212172211        34
20171212172227         4
20171212172237        17
20171212172251        26
20171212172330        48
20171212172389        47
20171212172445        41
20171212172446        51
20171212172494        48
20171212172501         6
20171212172523        16

[24361 rows x 1 columns]

Merge summary file and cps file by the respondent id

In [8]:
merged = summary.merge(cps_, left_on = 'TUCASEID', right_index = True)

In [9]:
merged

,TUCASEID,TUFINLWGT,TRYHHCHILD,TEAGE,TESEX,PEEDUCA,PTDTRACE,PEHSPNON,GTMETSTA,TELFS,...,t181699,t181801,t181899,t189999,t500101,t500103,t500105,t500106,t500107,GESTFIPS
0,20170101170002,5.217551e+06,15,34,2,39,2,2,1,1,...,0,0,0,0,0,0,0,0,0,26
1,20170101170012,3.106847e+06,7,28,2,40,1,2,1,5,...,0,0,0,0,0,0,0,0,0,12
2,20170101170027,1.653409e+07,15,15,1,35,3,2,1,5,...,0,0,0,0,0,0,0,0,0,35
3,20170101170030,1.757071e+07,-1,46,1,39,1,2,1,1,...,0,0,0,0,0,0,0,0,0,42
4,20170101170033,1.022275e+06,-1,85,1,44,1,1,1,1,...,0,0,0,0,0,0,0,0,0,53
5,20170101170079,2.972591e+06,-1,60,1,35,1,1,1,1,...,0,0,0,0,0,0,0,0,0,12
6,20170101170090,2.719770e+07,17,44,1,39,1,2,2,1,...,0,0,0,30,0,0,0,0,0,51
7,20170101170149,4.423197e+06,8,49,2,43,2,2,1,1,...,0,0,0,0,0,0,0,0,0,26
8,20170101170520,4.722745e+06,-1,63,1,40,1,2,1,1,...,0,0,0,0,0,0,0,0,0,25
9,20170101170521,5.431371e+06,-1,70,2,44,1,2,1,5,...,0,0,0,0,0,0,0,0,0,23
10,20170101170522,8.077136e+06,-1,44,2,40,1,2,1,1,...,0,0,0,0,0,0,0,0,0,25
11,20170101170539,1.050965e+07,1,17,2,36,1,2,2,5,...,0,0,0,0,0,0,0,0,0,13
12,20170101170551,1.380847e+07,-1,79,1,45,1,2,1,5,...,0,0,0,0,0,0,0,0,0,51
13,20170101170552,9.677182e+06,4,61,1,44,1,2,1,1,...,0,0,0,0,105,0,0,0,0,27
14,20170101170572,1.523992e+07,-1,50,2,39,1,2,2,1,...,0,0,0,0,0,0,0,0,0,18
15,20170101170574,5.723367e+06,-1,64,2,44,1,2,1,1,...,0,0,0,0,0,0,0,85,0,24
16,20170101170578,2.588656e+06,-1,22,2,39,1,1,1,5,...,0,0,0,0,0,0,0,0,0,6
17,20170101170595,2.782759e+06,12,46,1,43,1,1,1,1,...,0,0,0,0,0,0,0,0,0,4
18,20170101170596,3.578830e+06,3,52,1,39,1,1,1,1,...,0,0,0,0,0,0,0,0,0,6
19,20170101170598,1.087929e+07,10,47,2,43,2,2,1,1,...,0,0,0,0,0,0,0,0,0,12
20,20170101170612,6.071648e+06,-1,63,1,40,1,2,1,1,...,0,0,0,0,0,0,0,0,0,39
21,20170101170615,3.086205e+06,-1,50,2,40,2,2,2,5,...,0,0,0,0,0,0,0,0,0,24
22,20170101170639,3.467374e+06,-1,85,2,39,1,2,1,5,...,0,0,0,0,0,0,0,0,0,36
23,20170101170651,5.675642e+06,1,38,2,43,1,2,1,1,...,0,0,0,0,0,0,0,0,0,22
24,20170101170668,8.540110e+06,-1,64,2,41,1,2,1,5,...,0,0,0,0,0,0,0,0,0,13
25,20170101170687,1.820337e+06,-1,58,2,43,1,2,1,2,...,0,0,0,0,0,0,0,0,0,12
26,20170101170688,5.074716e+06,-1,51,2,40,1,2,1,1,...,0,0,0,0,0,0,0,0,0,49
27,20170101170710,4.260800e+06,-1,73,2,43,1,2,1,5,...,0,0,0,0,0,0,0,0,0,6
28,20170101170714,3.544166e+06,1,33,2,43,1,1,1,5,...,0,0,0,0,0,0,0,0,0,6
29,20170101170726,4.616305e+06,-1,59,1,39,1,2,2,1,...,0,0,0,0,0,0,0,0,0,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10193,20171212171874,1.259864e+07,1,32,1,46,1,2,1,1,...,0,0,0,0,0,0,0,0,0,4
10194,20171212171878,1.366772e+07,12,39,2,40,1,2,2,5,...,0,0,0,0,0,0,0,0,0,13
10195,20171212171881,2.904498e+06,1,38,1,42,1,2,1,2,...,0,0,0,0,0,0,0,0,0,49
10196,20171212171891,3.360232e+06,-1,80,2,40,1,2,1,5,...,0,0,0,0,0,0,0,0,0,6
10197,20171212171894,3.781476e+06,0,30,2,44,1,2,1,1,...,0,0,0,0,0,0,0,0,0,51
10198,20171212171895,1.316394e+07,0,32,2,44,1,2,1,1,...,0,0,0,0,0,0,0,0,0,17
10199,20171212171937,1.468183e+07,15,40,2,39,1,2,1,5,...,0,0,0,0,0,0,0,0,0,6
10200,20171212171938,6.467696e+06,7,52,2,40,1,2,2,5,...,0,0,0,0,0,0,0,0,0,39
10201,20171212171961,1.078649e+07,7,41,2,41,1,2,2,1,...,0,0,0,0,0,0,0,0,0,18
10202,20171212171999,4.433917e+06,-1,54,2,37,2,2,1,5,...,0,0,0,0,0,0,0,0,0,45
10203,20171212172005,3.255814e+07,-1,27,1,40,2,2,1,1,...,0,0,0,0,0,0,0,0,0,51
10204,20171212172017,1.726293e+07,-1,54,1,39,2,2,1,2,...,0,0,0,0,0,0,0,0,0,17
10205,20171212172026,3.649576e+06,9,41,2,43,1,2,1,1,...,0,0,0,0,0,0,0,0,0,46
10206,20171212172030,4.376136e+06,-1,70,2,44,1,2,1,2,...,0,0,0,0,0,0,0,0,0,39
10207,20171212172057,6.432773e+06,13,45,2,43,1,2,2,2,...,0,0,0,0,0,0,0,0,0,1
10208,20171212172062,1.636364e+07,-1,24,2,44,4,1,1,1,...,0,0,0,0,0,0,0,0,0,53
10209,20171212172072,5.871543e+06,-1,85,2,43,1,2,2,5,...,0,0,0,0,120,0,0,0,0,51
10210,20171212172083,1.012880e+07,2,43,1,33,1,1,2,2,...,0,0,0,0,0,0,0,0,0,56
10211,20171212172143,1.996493e+07,0,25,2,40,1,2,1,1,...,0,0,0,0,0,0,0,0,0,8
10212,20171212172208,2.653431e+07,-1,65,1,39,1,2,1,5,...,0,0,0,0,0,0,0,120,0,36
10213,20171212172211,9.835289e+06,-1,59,2,42,2,2,1,5,...,0,0,0,0,0,0,0,0,0,34
10214,20171212172227,9.599265e+06,-1,63,1,40,1,2,1,5,...,0,0,0,0,0,0,0,0,0,4
10215,20171212172251,6.878434e+06,11,41,1,43,1,2,1,2,...,0,0,0,0,0,0,0,0,0,26
10216,20171212172330,7.450325e+06,-1,74,2,40,1,2,1,5,...,0,0,0,0,0,0,0,0,0,48
10217,20171212172389,4.553109e+06,-1,76,2,40,1,2,2,5,...,0,0,0,0,0,0,0,0,0,47
10218,20171212172445,8.136896e+06,-1,36,2,42,1,2,1,1,...,0,0,0,0,0,0,0,0,0,41
10219,20171212172446,1.068679e+07,4,28,1,39,1,2,1,1,...,0,0,0,0,0,0,0,0,0,51
10220,20171212172494,1.016244e+07,-1,56,1,40,1,1,1,1,...,0,0,0,0,45,0,0,0,0,48
10221,20171212172501,4.120586e+06,5,36,2,43,1,1,1,2,...,0,0,0,0,20,0,0,120,0,6
10222,20171212172523,8.142193e+06,3,36,2,46,4,2,1,1,...,0,0,0,0,0,0,0,0,0,16

In [10]:
merged.head()

,TUCASEID,TUFINLWGT,TRYHHCHILD,TEAGE,TESEX,PEEDUCA,PTDTRACE,PEHSPNON,GTMETSTA,TELFS,...,t181699,t181801,t181899,t189999,t500101,t500103,t500105,t500106,t500107,GESTFIPS
0,20170101170002,5.217551e+06,15,34,2,39,2,2,1,1,...,0,0,0,0,0,0,0,0,0,26
1,20170101170012,3.106847e+06,7,28,2,40,1,2,1,5,...,0,0,0,0,0,0,0,0,0,12
2,20170101170027,1.653409e+07,15,15,1,35,3,2,1,5,...,0,0,0,0,0,0,0,0,0,35
3,20170101170030,1.757071e+07,-1,46,1,39,1,2,1,1,...,0,0,0,0,0,0,0,0,0,42
4,20170101170033,1.022275e+06,-1,85,1,44,1,1,1,1,...,0,0,0,0,0,0,0,0,0,53

Selected all the 'Relaxing and Leisure' columns. They start with 't1203'

In [11]:
leisure_columns = [x for x in merged.columns if x.startswith('t1203')]

work_columns = [x for x in merged.columns if x.startswith('t0501')]

Computed the average time spent for Relaxing and Leisure in each state

In [12]:
leisure_by_state = merged.loc[:, leisure_columns].groupby(merged.GESTFIPS).mean()

work_by_state = merged.loc[:, work_columns].groupby(merged.GESTFIPS).mean()

In [13]:
leisure_by_state

,t120301,t120302,t120303,t120304,t120305,t120306,t120307,t120308,t120309,t120310,t120311,t120312,t120313,t120399
GESTFIPS,,,,,,,,,,,,,,
1,49.065000,0.725000,206.890000,0.525000,2.075000,2.550000,17.875000,10.645000,0.000000,0.000000,0.000000,10.625000,0.125000,0.000000
2,29.900000,0.000000,140.400000,0.000000,0.000000,1.500000,4.500000,16.700000,22.350000,0.000000,0.000000,12.000000,0.000000,0.000000
4,12.000000,0.238938,177.592920,0.000000,1.637168,1.504425,15.783186,7.234513,1.393805,0.000000,0.000000,22.424779,0.066372,0.000000
5,21.962963,1.018519,204.861111,0.000000,0.898148,7.777778,9.398148,6.666667,0.555556,0.000000,0.000000,15.740741,0.000000,0.000000
6,21.861822,0.152508,158.803480,0.245650,0.296827,2.878199,11.572160,13.093142,2.629478,0.000000,0.015353,19.518936,0.214944,0.110542
8,11.930636,0.109827,147.820809,0.549133,0.000000,0.676301,14.485549,8.346821,2.283237,0.000000,0.693642,27.976879,0.000000,0.000000
9,15.211382,0.000000,161.056911,0.000000,0.487805,2.439024,6.000000,15.203252,1.601626,0.000000,0.000000,25.975610,0.000000,0.000000
10,12.500000,0.000000,227.142857,0.000000,0.892857,0.000000,1.964286,13.035714,0.000000,0.000000,0.000000,14.464286,1.071429,0.000000
11,33.392857,0.714286,177.142857,0.000000,8.571429,4.821429,9.642857,2.142857,0.000000,0.000000,0.000000,29.928571,0.000000,0.000000
12,26.575908,0.168317,201.250825,0.392739,0.463696,2.222772,13.090759,11.739274,0.575908,0.000000,0.000000,21.726073,0.016502,0.033003
13,23.356688,0.668790,206.480892,0.000000,1.576433,1.353503,8.496815,7.977707,2.484076,0.000000,1.417197,10.691083,1.624204,0.340764
15,19.655172,0.000000,152.965517,0.000000,0.000000,4.137931,19.137931,25.344828,1.896552,0.000000,0.000000,15.862069,4.137931,0.172414
16,18.289474,0.263158,176.684211,0.000000,0.789474,3.552632,28.973684,9.802632,0.000000,0.000000,2.368421,17.631579,0.000000,0.000000
17,15.057644,0.338346,187.601504,0.451128,2.390977,1.165414,11.340852,12.416040,0.864662,0.000000,0.000000,15.939850,0.200501,1.566416
18,27.765385,0.196154,184.576923,0.000000,1.153846,2.000000,18.038462,10.684615,4.269231,0.000000,0.230769,19.569231,0.923077,0.000000
19,11.328947,0.355263,187.934211,0.000000,1.052632,0.789474,20.546053,6.578947,0.197368,0.000000,0.000000,25.710526,0.578947,0.723684
20,11.902439,0.601626,176.504065,0.000000,4.756098,1.991870,13.268293,15.447154,1.463415,0.000000,0.000000,22.593496,0.731707,0.000000
21,28.615854,0.792683,201.115854,0.365854,1.628049,1.158537,8.536585,6.341463,2.500000,0.000000,0.000000,24.347561,0.000000,0.000000
22,29.601266,0.145570,221.335443,0.000000,1.588608,1.234177,9.202532,8.575949,0.000000,0.000000,0.000000,10.632911,0.094937,0.000000
23,29.024390,0.219512,137.609756,0.000000,3.170732,0.731707,19.731707,14.243902,9.024390,0.000000,0.000000,30.560976,0.000000,0.000000
24,23.388601,0.103627,173.378238,0.000000,0.155440,3.937824,9.575130,12.150259,0.932642,0.000000,0.000000,18.440415,0.233161,0.000000
25,13.940367,0.252294,177.866972,0.000000,3.096330,1.788991,10.128440,10.357798,3.761468,0.412844,0.000000,22.279817,0.275229,0.068807
26,20.172524,0.249201,182.169329,0.191693,1.376997,0.670927,19.980831,14.674121,2.587859,0.000000,0.000000,21.725240,0.191693,0.000000
27,21.810811,0.389189,153.513514,0.324324,4.518919,1.529730,12.967568,11.167568,1.783784,0.000000,0.000000,25.718919,0.000000,0.648649
28,34.887931,0.387931,205.422414,3.913793,2.025862,5.681034,6.379310,6.336207,0.000000,0.000000,0.000000,20.534483,0.000000,0.000000
29,20.515789,0.394737,180.247368,2.368421,0.000000,1.968421,12.989474,13.294737,0.000000,0.000000,0.631579,14.357895,0.000000,0.000000
30,22.513514,0.000000,156.648649,0.000000,3.243243,0.000000,28.324324,8.702703,21.081081,0.000000,0.000000,32.594595,0.000000,0.000000
31,17.594203,0.652174,179.681159,0.000000,3.478261,2.608696,17.898551,22.405797,9.420290,0.000000,0.000000,14.202899,0.000000,0.217391
32,23.704762,0.228571,214.885714,0.000000,1.285714,0.809524,17.380952,10.238095,4.000000,0.000000,2.380952,19.047619,0.000000,0.000000
33,12.934783,0.000000,160.369565,0.000000,1.304348,8.543478,4.565217,6.413043,0.326087,0.000000,0.000000,13.369565,0.000000,0.000000
34,16.322034,0.000000,199.918644,0.000000,5.098305,2.084746,8.559322,7.654237,1.271186,0.000000,0.000000,14.315254,0.610169,0.000000
35,23.432692,0.192308,172.096154,0.000000,1.615385,2.057692,9.663462,5.673077,1.778846,0.000000,0.000000,20.192308,0.000000,3.894231
36,28.473373,0.394477,172.516765,0.000000,1.001972,1.471400,19.856016,10.790927,0.676529,0.000000,0.118343,23.771203,0.688363,0.641026
37,21.203704,0.043210,169.811728,1.018519,0.308642,1.342593,14.533951,11.870370,0.462963,0.000000,0.000000,11.574074,0.000000,0.000000
38,21.652174,0.652174,214.478261,0.000000,0.000000,0.000000,13.043478,5.217391,0.000000,0.000000,0.000000,13.695652,0.000000,0.000000
39,21.528902,1.069364,199.101156,0.563584,1.109827,1.994220,13.898844,13.156069,0.317919,0.000000,0.000000,13.991329,0.786127,0.000000
40,24.482014,0.575540,216.057554,0.503597,0.215827,0.215827,21.424460,7.618705,0.431655,0.000000,0.827338,20.388489,0.000000,0.000000
41,18.919540,0.264368,166.379310,0.000000,1.080460,2.482759,18.293103,17.126437,1.896552,0.000000,0.114943,19.390805,0.718391,0.000000
42,27.296954,0.489848,193.687817,0.152284,2.675127,1.383249,12.281726,10.944162,2.393401,0.000000,0.000000,24.614213,0.164975,1.289340
44,5.156250,0.000000,167.437500,0.000000,0.000000,1.875000,28.343750,11.250000,0.625000,0.000000,0.000000,45.187500,0.000000,0.000000
45,39.725962,0.000000,201.413462,0.975962,2.620192,1.855769,10.610577,6.923077,1.432692,0.000000,0.000000,17.701923,0.000000,0.000000
46,23.050000,0.150000,182.350000,0.000000,0.125000,0.000000,19.000000,5.500000,0.000000,0.000000,0.000000,3.375000,0.000000,0.000000
47,35.100840,0.752101,176.596639,0.000000,0.357143,4.306723,12.008403,7.289916,0.210084,0.252101,0.000000,22.802521,0.000000,0.441176
48,21.819899,0.308564,184.476071,0.113350,2.217884,1.492443,10.731738,7.272040,2.537783,0.000000,0.554156,16.332494,0.050378,0.075567
49,8.400000,0.500000,133.916667,0.000000,0.000000,0.666667,17.833333,9.458333,0.166667,0.000000,3.258333,19.700000,2.583333,0.000000
50,14.166667,0.000000,139.722222,0.000000,0.000000,0.000000,0.000000,11.555556,3.333333,0.000000,0.000000,45.000000,6.666667,0.000000
51,24.332046,0.308880,173.583012,0.463320,2.722008,2.432432,4.606178,10.270270,2.625483,0.077220,0.463320,20.706564,0.000000,1.158301
53,12.863071,0.751037,155.120332,0.124481,3.045643,3.153527,14.273859,11.004149,1.244813,0.000000,0.373444,17.929461,1.535270,0.497925
54,45.971429,0.214286,270.900000,0.000000,1.714286,0.000000,10.357143,8.071429,4.885714,0.000000,0.000000,21.557143,0.428571,0.000000
55,15.604878,0.395122,159.156098,0.000000,2.585366,4.063415,13.687805,12.907317,2.341463,0.000000,1.170732,22.858537,0.146341,1.097561
56,0.000000,0.000000,194.533333,0.000000,0.000000,0.000000,30.666667,0.000000,0.000000,0.000000,0.000000,37.333333,0.000000,0.000000

In [14]:
# merged.assign(leisure_columns=lambda x: )
# merged.assign['leisure']

In [15]:
merged.loc[:, 'TUCASEID']

0        20170101170002
1        20170101170012
2        20170101170027
3        20170101170030
4        20170101170033
5        20170101170079
6        20170101170090
7        20170101170149
8        20170101170520
9        20170101170521
10       20170101170522
11       20170101170539
12       20170101170551
13       20170101170552
14       20170101170572
15       20170101170574
16       20170101170578
17       20170101170595
18       20170101170596
19       20170101170598
20       20170101170612
21       20170101170615
22       20170101170639
23       20170101170651
24       20170101170668
25       20170101170687
26       20170101170688
27       20170101170710
28       20170101170714
29       20170101170726
              ...
10193    20171212171874
10194    20171212171878
10195    20171212171881
10196    20171212171891
10197    20171212171894
10198    20171212171895
10199    20171212171937
10200    20171212171938
10201    20171212171961
10202    20171212171999
10203    20171212172005
10204    20171212172017
10205    20171212172026
10206    20171212172030
10207    20171212172057
10208    20171212172062
10209    20171212172072
10210    20171212172083
10211    20171212172143
10212    20171212172208
10213    20171212172211
10214    20171212172227
10215    20171212172251
10216    20171212172330
10217    20171212172389
10218    20171212172445
10219    20171212172446
10220    20171212172494
10221    20171212172501
10222    20171212172523
Name: TUCASEID, Length: 10223, dtype: int64

In [16]:
leisure_by_state.head()

,t120301,t120302,t120303,t120304,t120305,t120306,t120307,t120308,t120309,t120310,t120311,t120312,t120313,t120399
GESTFIPS,,,,,,,,,,,,,,
1,49.065000,0.725000,206.890000,0.52500,2.075000,2.550000,17.875000,10.645000,0.000000,0.0,0.000000,10.625000,0.125000,0.000000
2,29.900000,0.000000,140.400000,0.00000,0.000000,1.500000,4.500000,16.700000,22.350000,0.0,0.000000,12.000000,0.000000,0.000000
4,12.000000,0.238938,177.592920,0.00000,1.637168,1.504425,15.783186,7.234513,1.393805,0.0,0.000000,22.424779,0.066372,0.000000
5,21.962963,1.018519,204.861111,0.00000,0.898148,7.777778,9.398148,6.666667,0.555556,0.0,0.000000,15.740741,0.000000,0.000000
6,21.861822,0.152508,158.803480,0.24565,0.296827,2.878199,11.572160,13.093142,2.629478,0.0,0.015353,19.518936,0.214944,0.110542

In [17]:
work_by_state.head()

             t050101   t050102  t050103   t050104  t050199
GESTFIPS
1         117.845000  1.950000      0.0  0.050000      0.0
2         179.000000  9.000000      0.0  0.000000      0.0
4         123.960177  5.269912      0.0  0.000000      0.0
5         136.444444  2.638889      0.0  0.407407      0.0
6         139.303992  2.360287      0.0  0.109519      0.0

In [18]:
time_spent = merged.loc[:, ['TUCASEID']+leisure_columns].set_index('TUCASEID').sum(axis=1)

In [19]:
time_spent.shape[0]

10223

In [20]:
#np.histogram?

In [21]:
# time_spent.hist?

In [22]:
#counts

In [23]:
#bins

In [24]:
# def normalized_histogram(data, bins=10):
#     counts, bins = np.histogram(data, bins=bins)
#     counts = 100*counts/counts.sum()
#     sc_x2 = bq.LinearScale()
#     sc_y2 = bq.LinearScale()
#     ax_x2 = bq.Axis(label = 'Time spent', scale=sc_x2, tick_rotate=90, tick_offset = '-16em')
#     ax_y2 = bq.Axis(label='Frequency%', scale=sc_y2,orientation='vertical', tick_offset='3.5em')
  
#     bars = bq.Bars(x=bins[:-1], y=counts, align='left', scales={'x': sc_x2, 'y': sc_y2})
# #           ,width=bins[1]-bins[0]  , edgecolor='black')
#     figure = bq.Figure(marks = [bars],axes=[ax_x2, ax_y2])
# #     plt.xticks(bins, rotation=90);
# #     plt.xlabel('Time spent in minutes')
# #     plt.ylabel('Frequency%')
    
#     return figure

## Map

In [25]:
cscale = bq.ColorScale(scheme = 'viridis')
                       # reverse the colorscale or Hawaii is not visible
                     
map_tt = bq.Tooltip(labels = ['State', 'Time Spent (minutes)'], fields = ['name', 'color'])
sc_geo = bq.AlbersUSA()
states_map = bq.Map(color = leisure_by_state.sum(axis=1).round(1).to_dict(), 
                     map_data=bq.topo_load('map_data/USStatesMap.json'),
                    scales = {'projection':sc_geo, 'color':cscale}, 
                   tooltip = map_tt)

cax = bq.ColorAxis(scale=cscale, orientation='vertical', side='left')
fig = bq.Figure(marks=[states_map],axes=[cax], title = 'Average time spent for leisure')
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='viridis'), side='left')], fig_margin={â€¦

In [26]:
cscale = bq.ColorScale(scheme = 'viridis')
                       # reverse the colorscale or Hawaii is not visible
                     
map_tt = bq.Tooltip(labels = ['State', 'Time Spent (minutes)'], fields = ['name', 'color'])
sc_geo = bq.AlbersUSA()
states_map = bq.Map(color = work_by_state.sum(axis=1).round(1).to_dict(), 
                     map_data=bq.topo_load('map_data/USStatesMap.json'),
                    scales = {'projection':sc_geo, 'color':cscale}, 
                   tooltip = map_tt)

cax = bq.ColorAxis(scale=cscale, orientation='vertical', side='left')
fig = bq.Figure(marks=[states_map],axes=[cax], title = 'Average time spent for work')
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='viridis'), side='left')], fig_margin={â€¦

## Histogram

In [27]:
def normalized_hist(data, bins=10):
    counts, bins = np.histogram(data, bins=bins)
    counts = counts*100/counts.sum()
    return bins, counts

In [28]:
sc_x2 = bq.LinearScale()
sc_y2 = bq.LinearScale()
ax_x2 = bq.Axis(label = 'Time spent for leisure', scale=sc_x2, tick_offset = '2000em')
ax_y2 = bq.Axis(label='Frequency%', scale=sc_y2,orientation='vertical')
x, y = normalized_hist(time_spent, bins=14)
bars = bq.Bars(x = x[:-1], y=y, align='left', scales={'x': sc_x2, 'y': sc_y2})
#           ,width=bins[1]-bins[0]  , edgecolor='black')
figure = bq.Figure(marks = [bars],axes=[ax_x2, ax_y2])
figure

Figure(axes=[Axis(label='Time spent for leisure', scale=LinearScale()), Axis(label='Frequency%', orientation='â€¦

In [29]:
merged.head()

,TUCASEID,TUFINLWGT,TRYHHCHILD,TEAGE,TESEX,PEEDUCA,PTDTRACE,PEHSPNON,GTMETSTA,TELFS,...,t181699,t181801,t181899,t189999,t500101,t500103,t500105,t500106,t500107,GESTFIPS
0,20170101170002,5.217551e+06,15,34,2,39,2,2,1,1,...,0,0,0,0,0,0,0,0,0,26
1,20170101170012,3.106847e+06,7,28,2,40,1,2,1,5,...,0,0,0,0,0,0,0,0,0,12
2,20170101170027,1.653409e+07,15,15,1,35,3,2,1,5,...,0,0,0,0,0,0,0,0,0,35
3,20170101170030,1.757071e+07,-1,46,1,39,1,2,1,1,...,0,0,0,0,0,0,0,0,0,42
4,20170101170033,1.022275e+06,-1,85,1,44,1,1,1,1,...,0,0,0,0,0,0,0,0,0,53

# Linked Visualization

In [30]:
cscale = bq.ColorScale(scheme = 'viridis')        
                   # reverse the colorscale or Hawaii is not visible

map_tt = bq.Tooltip(labels = ['State', 'Leisure time (minutes)'], fields = ['name', 'color'])
sc_geo = bq.AlbersUSA()
states_map = bq.Map(color = leisure_by_state.sum(axis=1).round(1).to_dict(), 
                     map_data=bq.topo_load('map_data/USStatesMap.json'),
                    scales = {'projection':sc_geo, 'color':cscale},tooltip = map_tt,
                    interactions = {'click': 'select', 'hover':'tooltip', },
                    anchor_style = {'fill':'red'}, 
                    selected_style = {'opacity': 1.0},
                    unselected_style = {'opacity': 1.0})

cax = bq.ColorAxis(scale=cscale, orientation='vertical', side='left')
fig_map = bq.Figure(marks=[states_map],axes=[cax], title = 'Average time spent for leisure')
fig_map.fig_margin = {'bottom': 10, 'top': 10, 'left': 0, 'right': 0}

        
        
# Bar chart
sc_x2 = bq.LinearScale()
sc_y2 = bq.LinearScale()
ax_x2 = bq.Axis(label = 'Time spent for leisure(minutes)', scale=sc_x2, orientation='horizontal')
ax_y2 = bq.Axis(label='Frequency%', scale=sc_y2,orientation='vertical')
x, y = normalized_hist(time_spent, bins=14)
bars = bq.Bars(x = x[:-1], y=y, align='right', scales={'x': sc_x2, 'y': sc_y2})
#           ,width=bins[1]-bins[0]  , edgecolor='black')
fig_bar = bq.Figure(marks = [bars],axes=[ax_x2, ax_y2])
# fig_bar.fig_margin = {'bottom':50, 'top':50, 'left':20, 'right':10}

# def onClickButton(a):
#     if (a.description == "Job Search Time"):
        
#         cscale = bq.ColorScale(scheme = 'viridis')        
                      
#         map_tt = bq.Tooltip(labels = ['State', 'Job Search Time (minutes)'], fields = ['name', 'color'])
#         sc_geo = bq.AlbersUSA()
#         states_map = bq.Map(color = travelling_by_state.sum(axis=1).round(1).to_dict(), 
#                              map_data=bq.topo_load('map_data/USStatesMap.json'),
#                             scales = {'projection':sc_geo, 'color':cscale},tooltip = map_tt,
#                             interactions = {'click': 'select', 'hover':'tooltip', },
#                             anchor_style = {'fill':'red'}, 
#                             selected_style = {'opacity': 1.0},
#                             unselected_style = {'opacity': 1.0})

#         cax = bq.ColorAxis(scale=cscale, orientation='vertical', side='left')
#         fig_map = bq.Figure(marks=[states_map],axes=[cax], title = 'Average time spent for travelling')
#         fig_map.fig_margin = {'bottom': 10, 'top': 0, 'left': 25, 'right': 10}


def on_select(change):
    
    if not change['new']:
        selected_fips = merged.GESTFIPS.unique()
    else:
        selected_fips = change['new']
        states_map.selected = [selected_fips[-1]]
    activity = activity_dropdown.value #Leisure time
    if activity == 'Leisure Time':
        columns = [x for x in merged.columns if x.startswith('t1203')]
    elif activity == 'Work Time':
        columns = [x for x in merged.columns if x.startswith('t0501')]
    x, y = normalized_hist(merged
                            .loc[merged.GESTFIPS.isin(selected_fips), ['TUCASEID']+columns]
                            .set_index('TUCASEID')
                            .sum(axis=1), bins=14)
    bars.x = x
    bars.y = y
states_map.observe(on_select, 'selected')

activity_dropdown = ipywidgets.Dropdown(options = ['Leisure Time','Work Time'],
                    value='Leisure Time', Description = 'Select activity')

# B_leisure_Time = ipywidgets.Button(description = "leisure Time")
# JobSearchTime = ipywidgets.Button(description = "Job Search Time")


#B_leisure_Time.on_click(onClickButton)
# JobSearchTime.on_click(onClickButton)








def on_activity_change(change):
    states_map.selected=[]
    activity = activity_dropdown.value #Leisure time
    if activity == 'Leisure Time':
        columns = [x for x in merged.columns if x.startswith('t1203')]
        ax_x2.label = 'Time spent for leisure(minutes)'
        fig_map.title = 'Average time spent for leisure'
        map_tt.labels = ['State', 'Leisure time (minutes)']
    elif activity == 'Work Time':
        columns = [x for x in merged.columns if x.startswith('t0501')]
        ax_x2.label = 'Time spent working(minutes)'
        fig_map.title = 'Average time spent working'
        map_tt.labels = ['State', 'Working time (minutes)']
    filtered = merged.loc[:, columns].groupby(merged.GESTFIPS).mean().sum(axis=1).round(1).to_dict()
    states_map.color = filtered
    

activity_dropdown.observe(on_activity_change, 'value')
ipywidgets.VBox([activity_dropdown,ipywidgets.HBox([fig_map, fig_bar])])

VBox(children=(Dropdown(options=('Leisure Time', 'Work Time'), value='Leisure Time'), HBox(children=(Figure(axâ€¦